name: Generate and Deploy RSS Feed

on:
  schedule:
    - cron: '0 */2 * * *'    # Every 2 hours 
    - cron: '0 */12 * * *'   # Every 12 hours 

  workflow_dispatch:

jobs:
  generate_feed:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Hong_Kong  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for branch operations

      - name: Fetch gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages --force
          mkdir -p gh-pages-deploy
          git --work-tree=gh-pages-deploy checkout gh-pages -- .

      - name: Cache pip dependencies
        uses: actions/cache@v3
        id: pip-cache
        with:
          path: |
            ~/.cache/pip
            venv/
          key: pip-${{ hashFiles('requirements.txt') }}-${{ runner.os }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
        env:
          PIP_CACHE_DIR: ~/.cache/pip

      - name: Generate RSS feeds
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            python hkdiscuss.py --feeds money house hottopics
            python hknet.py
          elif [[ "${{ github.event.schedule }}" == "0 */2 * * *" ]]; then
            python hkdiscuss.py --feeds money house
            python hknet.py
          else
            python hkdiscuss.py --feeds hottopics
          fi
              
      - name: Check generated files
        run: |
          if [ ! -f *.xml ]; then
            echo "No XML files generated."
            exit 1
          fi

      - name: Clean up old deployment
        run: rm -rf gh-pages-deploy

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          mkdir -p gh-pages-deploy
          if git show-ref --quiet refs/remotes/origin/gh-pages; then
            git worktree add gh-pages-deploy gh-pages
          else
            git worktree add --orphan gh-pages-deploy
            cd gh-pages-deploy
            git commit --allow-empty -m "Initialize gh-pages"
            git push origin gh-pages
            cd ..
          fi

          mv *.xml gh-pages-deploy/
          cd gh-pages-deploy
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update feeds $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin gh-pages
          fi
