name: Generate Feed

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  generate_feed:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate RSS feeds
        run: python rss.py  # This generates hkdiscuss_feed.xml and hket_feed.xml

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Checkout gh-pages branch
          if git ls-remote --exit-code --heads origin gh-pages; then
            git fetch origin gh-pages
            git checkout gh-pages --force
          else
            git checkout --orphan gh-pages
            git rm -rf .
            echo "<h1>RSS Feeds</h1>" > index.html
          fi
          
          # Copy the generated XML files FROM CURRENT DIRECTORY
          cp hkdiscuss_feed.xml ./
          cp hket_feed.xml ./
          
          git add .
          git commit -m "Update feeds - $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin gh-pages --force
